---
version: '3'

services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - ./data/:/var/www/html/
    links:
      - fpm
  fpm:
    image: php:fpm-alpine
    volumes:
      - ./data/:/var/www/html/
...